### ISSUE TITLE
Domain validator breaks on hyphens

### ISSUE THREAD

**Issue by lgommans** [grommunio/admin-api#2]
https://github.com/grommunio/admin-api/blob/master/cli/remote.py#L33

Was just browsing the code and noticed this domain validator. It does not match `https://game-maker.nl` though that domain is quite valid. Also, it works for IPv4 addresses, but not IPv6; not sure if IP address support (in the v4 case) is intentional but it seems convenient to have.

- To resolve support for domains with hyphens, `\w\.` should probably have a `-` appended.
- To add support for IPv6, it depends on what format you want but probably (given that specifying the port is possible) it makes most sense to require `[` square brackets `]` around the address. The address itself only needs `:` to be added before the `-` I think, but this might cause issues for `https://:8080` (which should be invalid) parsing with `:` as host or so so perhaps this needs to be turned into a two-case system where the `:` is only allowed inside `[]`.

Or perhaps using `urllib.parse` is easier.

**Comment by juliaschroeder** [comment]
Sorry for the late reply.
Yes, the hyphen was missing, thanks for the heads up.
Unfortunately `urllib.parse` does not do what is wanted here. As it is intended for parsing (potentially relative) URLs, the inputs `localhost`, `http://localhost` and `localhost:8080` would each be parsed into different components (path, scheme and netloc, scheme and path).
Support for IPv6 addresses may be added in the future.
The issue was fixed in  bed8d21572a28dbd93d6fd67b7783f44af21e502.
